"""MCP server exposing zeus-generated sqlite datasets.

One tool per access pattern an LLM client needs: discover what datasets and
tables exist, inspect a table's shape, pull rows directly, or run read-only
SQL for anything more specific. All reads go through :mod:`zaia.data`, which
enforces read-only access at the sqlite connection layer.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP

from zaia import data

mcp = FastMCP(
    "zaia",
    instructions=(
        "Query synthetic datasets generated by zeus. Call list_datasets() first "
        "to see what's available, then describe_table() before querying an "
        "unfamiliar table."
    ),
)

_data_dir = Path("output")


def configure(data_dir: Path) -> None:
    """Set the directory zaia scans for zeus sqlite output. Call once before run()."""
    global _data_dir
    _data_dir = data_dir


def _connect(dataset: str):
    db_path = data.resolve_db(_data_dir, dataset)
    return data.connect_ro(db_path)


@mcp.tool()
def list_datasets() -> list[dict[str, Any]]:
    """List available datasets (one per zeus use case) and their tables."""
    datasets = data.discover_datasets(_data_dir)
    result = []
    for name, db_path in datasets.items():
        con = data.connect_ro(db_path)
        try:
            result.append({"dataset": name, "tables": data.list_tables(con)})
        finally:
            con.close()
    return result


@mcp.tool()
def list_tables(dataset: str) -> list[dict[str, Any]]:
    """List tables and row counts for a dataset."""
    con = _connect(dataset)
    try:
        return data.list_tables(con)
    finally:
        con.close()


@mcp.tool()
def describe_table(dataset: str, table: str) -> dict[str, Any]:
    """Get a table's columns (name + declared type) and one sample row."""
    con = _connect(dataset)
    try:
        return data.table_schema(con, table)
    finally:
        con.close()


@mcp.tool()
def get_table(dataset: str, table: str, limit: int = 100, offset: int = 0) -> list[dict[str, Any]]:
    """Fetch rows from a table, no SQL required. limit is capped at 1000."""
    con = _connect(dataset)
    try:
        return data.get_table(con, table, limit=limit, offset=offset)
    finally:
        con.close()


@mcp.tool()
def query(dataset: str, sql: str, limit: int = 200) -> list[dict[str, Any]]:
    """Run a read-only SQL query (SELECT/WITH only) against a dataset. limit is capped at 5000."""
    con = _connect(dataset)
    try:
        return data.run_query(con, sql, limit=limit)
    finally:
        con.close()


@mcp.resource("zaia://{dataset}/schema")
def dataset_schema(dataset: str) -> str:
    """Full table/column listing for a dataset, as browsable JSON."""
    con = _connect(dataset)
    try:
        tables = [t["table"] for t in data.list_tables(con)]
        schema = {"dataset": dataset, "tables": [data.table_schema(con, t) for t in tables]}
    finally:
        con.close()
    return json.dumps(schema, indent=2, default=str)
